// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Post from "./post.bs.js";
import * as React from "react";
import * as Belt_Array from "bs-platform/lib/es6/belt_Array.js";

function s(prim) {
  return prim;
}

function PostFeed$PostItem(Props) {
  var post = Props.post;
  var title = Post.title(post);
  var author = Post.author(post);
  var text = Post.text(post);
  var textDivs = Belt_Array.map(text, (function (x) {
          return React.createElement("p", {
                      className: "mb-1 text-sm"
                    }, x);
        }));
  return React.createElement("div", {
              className: "bg-green-700 hover:bg-green-900 text-gray-300 hover:text-gray-100 px-8 py-4 mb-4"
            }, React.createElement("h2", {
                  className: "text-2xl mb-1"
                }, title), React.createElement("h3", {
                  className: "mb-4"
                }, author), textDivs, React.createElement("button", {
                  className: "mr-4 mt-4 bg-red-500 hover:bg-red-900 text-white py-2 px-4"
                }, "Remove this post"));
}

var PostItem = {
  make: PostFeed$PostItem
};

function PostFeed$PostsView(Props) {
  var posts = Props.posts;
  var postItems = Belt_Array.map(posts, (function (post) {
          return React.createElement(PostFeed$PostItem, {
                      post: post,
                      key: Post.id(post)
                    });
        }));
  return React.createElement("div", {
              className: "max-w-3xl mx-auto mt-8 relative"
            }, postItems);
}

var PostsView = {
  make: PostFeed$PostsView
};

function reducer(state, action) {
  return state;
}

var initialState = {
  posts: Post.examples,
  forDeletion: undefined
};

function PostFeed(Props) {
  React.useReducer(reducer, initialState);
  return React.createElement(PostFeed$PostsView, {
              posts: Post.examples
            });
}

var make = PostFeed;

export {
  s ,
  PostItem ,
  PostsView ,
  reducer ,
  initialState ,
  make ,
  
}
/* Post Not a pure module */
